# Generated by Django 4.2.16 on 2024-12-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentapp', '0004_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
